<x-layouts.app>
    <div class="mb-6 flex flex-wrap items-start justify-between gap-4">
        <div><a href="{{ route('admin.contacts.index') }}" class="text-sm text-blue-600 hover:underline">← Volver a contactos</a><h1 class="mt-2 text-2xl font-bold text-gray-800 dark:text-gray-100">{{ $contact->name }}</h1><p class="mt-1 text-gray-600 dark:text-gray-400">Consulta recibida el {{ $contact->created_at->format('d/m/Y \a \l\a\s H:i') }}.</p></div>
        <form action="{{ route('admin.contacts.update', $contact) }}" method="POST" class="flex items-center gap-2">@csrf @method('PUT')<label for="status" class="sr-only">Estado</label><select id="status" name="status" class="rounded-md border-gray-300 p-2 dark:border-gray-700 dark:bg-gray-900">@foreach (['nuevo' => 'Nuevo', 'leido' => 'Leído', 'respondido' => 'Respondido', 'archivado' => 'Archivado'] as $value => $label)<option value="{{ $value }}" @selected($contact->status === $value)>{{ $label }}</option>@endforeach</select><button class="rounded-md bg-blue-600 px-4 py-2 font-medium text-white hover:bg-blue-700">Guardar</button></form>
    </div>

    <div class="grid gap-6 lg:grid-cols-3">
        <section class="lg:col-span-2 rounded-lg border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-700 dark:bg-gray-800"><h2 class="text-lg font-semibold">Mensaje</h2><p class="mt-4 whitespace-pre-line leading-relaxed text-gray-700 dark:text-gray-300">{{ $contact->message }}</p></section>
        <aside class="space-y-6 rounded-lg border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-700 dark:bg-gray-800"><div><h2 class="text-lg font-semibold">Datos de contacto</h2><dl class="mt-4 space-y-3 text-sm"><div><dt class="text-gray-500">Correo</dt><dd><a class="text-blue-600 hover:underline" href="mailto:{{ $contact->email }}">{{ $contact->email }}</a></dd></div><div><dt class="text-gray-500">Teléfono</dt><dd>{{ $contact->phone ?: 'No informado' }}</dd></div><div><dt class="text-gray-500">Empresa u organización</dt><dd>{{ $contact->company ?: 'No informada' }}</dd></div><div><dt class="text-gray-500">Motivo</dt><dd>{{ str_replace('_', ' ', ucfirst($contact->inquiry_type)) }}</dd></div></dl></div><div><h2 class="text-lg font-semibold">Servicios de interés</h2><div class="mt-3 flex flex-wrap gap-2">@forelse ($contact->services as $service)<span class="rounded bg-gray-100 px-2 py-1 text-xs dark:bg-gray-700">{{ $service->name }}</span>@empty <span class="text-sm text-gray-500">No informó servicios.</span>@endforelse</div></div></aside>
    </div>
</x-layouts.app>
